[package]
name = "tp7"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }

[[bin]]
name = "dns_server"
path = "src/server.rs"

[[bin]]
name = "dns_client"  
path = "src/client.rs"
